#pragma once

#include "Audio.hpp"

#include <array>
#include <cstdint>

constexpr inline std::uint16_t bpm = 180;

#define div(d) (60 * 1000000 / bpm / d)

constexpr inline std::array musical_score{
    // 1
    Note{E5,       div(1)},
    Note{B4,       div(2)},
    Note{C5,       div(2)},
    Note{D5,       div(2)},
    Note{E5,       div(4)},
    Note{D5,       div(4)},
    Note{C5,       div(2)},
    Note{B4,       div(2)},
    // 2
    Note{A4,       div(1)},
    Note{A4,       div(2)},
    Note{C5,       div(2)},
    Note{E5,       div(1)},
    Note{D5,       div(2)},
    Note{C5,       div(2)},
    // 3
    Note{B4,       div(1)},
    Note{B4,       div(4)},
    Note{B4,       div(4)},
    Note{C5,       div(2)},
    Note{D5,       div(1)},
    Note{E5,       div(1)},
    // 4
    Note{C5,       div(1)},
    Note{A4,       div(1)},
    Note{A4,       div(1)},
    Note{O,        div(1)},

    // 5
    Note{D5,       div(1)},
    Note{D5,       div(2)},
    Note{F5,       div(2)},
    Note{A5,       div(1)},
    Note{G5,       div(2)},
    Note{F5,       div(2)},
    // 6
    Note{E5,       div(1)},
    Note{E5,       div(2)},
    Note{C5,       div(2)},
    Note{E5,       div(1)},
    Note{D5,       div(2)},
    Note{C5,       div(2)},
    // 7
    Note{B4,       div(1)},
    Note{B4,       div(4)},
    Note{B4,       div(4)},
    Note{C5,       div(2)},
    Note{D5,       div(1)},
    Note{E5,       div(1)},
    // 8
    Note{C5,       div(1)},
    Note{A4,       div(1)},
    Note{A4,       div(1)},
    Note{O,        div(1)},

    // 9
    Note{E5,       div(1)},
    Note{B4,       div(2)},
    Note{C5,       div(2)},
    Note{D5,       div(2)},
    Note{E5,       div(4)},
    Note{D5,       div(4)},
    Note{C5,       div(2)},
    Note{B4,       div(2)},
    // 10
    Note{A4,       div(1)},
    Note{A4,       div(2)},
    Note{C5,       div(2)},
    Note{E5,       div(1)},
    Note{D5,       div(2)},
    Note{C5,       div(2)},
    // 11
    Note{B4,       div(1)},
    Note{B4,       div(2)},
    Note{C5,       div(2)},
    Note{D5,       div(1)},
    Note{E5,       div(1)},
    // 12
    Note{C5,       div(1)},
    Note{A4,       div(1)},
    Note{A4,       div(1)},
    Note{O,        div(1)},

    // 13
    Note{D5,       div(1)},
    Note{D5,       div(2)},
    Note{F5,       div(2)},
    Note{A5,       div(1)},
    Note{G5,       div(2)},
    Note{F5,       div(2)},
    // 14
    Note{E5,       div(1)},
    Note{E5,       div(2)},
    Note{C5,       div(2)},
    Note{E5,       div(1)},
    Note{D5,       div(2)},
    Note{C5,       div(2)},
    // 15
    Note{B4,       div(1)},
    Note{B4,       div(2)},
    Note{C5,       div(2)},
    Note{D5,       div(1)},
    Note{E5,       div(1)},
    // 16
    Note{C5,       div(1)},
    Note{A4,       div(1)},
    Note{A4,       div(1)},
    Note{O,        div(1)},

    // 17
    Note{E5,       div(1)},
    Note{O,        div(1)},
    Note{C5,       div(1)},
    Note{O,        div(1)},
    // 18
    Note{D5,       div(1)},
    Note{O,        div(1)},
    Note{B4,       div(1)},
    Note{O,        div(1)},
    // 19
    Note{C5,       div(1)},
    Note{O,        div(1)},
    Note{A4,       div(1)},
    Note{O,        div(1)},
    // 20
    Note{G4,       div(1)},
    Note{O,        div(1)},
    Note{B4,       div(1)},
    Note{O,        div(1)},

    // 21
    Note{E5,       div(1)},
    Note{O,        div(1)},
    Note{C5,       div(1)},
    Note{O,        div(1)},
    // 22
    Note{D5,       div(1)},
    Note{O,        div(1)},
    Note{B4,       div(1)},
    Note{O,        div(1)},
    // 23
    Note{C5,       div(1)},
    Note{E5,       div(1)},
    Note{A5,       div(1)},
    Note{A5,       div(1)},
    // 24
    Note{G5_Sharp, div(1)},
    Note{O,        div(1)},
    Note{O,        div(1)},
    Note{O,        div(1)},

    // 25
    Note{E5,       div(1)},
    Note{B4,       div(2)},
    Note{C5,       div(2)},
    Note{D5,       div(1)},
    Note{C5,       div(2)},
    Note{B4,       div(2)},
    // 26
    Note{A4,       div(1)},
    Note{A4,       div(2)},
    Note{C5,       div(2)},
    Note{E5,       div(1)},
    Note{D5,       div(2)},
    Note{C5,       div(2)},
    // 27
    Note{B4,       div(1)},
    Note{O,        div(1)},
    Note{D5,       div(1)},
    Note{E5,       div(1)},
    // 28
    Note{C5,       div(1)},
    Note{A4,       div(1)},
    Note{A4,       div(1)},
    Note{O,        div(1)},

    // 29
    Note{D5,       div(1)},
    Note{D5,       div(2)},
    Note{F5,       div(2)},
    Note{A5,       div(1)},
    Note{G5,       div(2)},
    Note{F5,       div(2)},
    // 30
    Note{E5,       div(1)},
    Note{E5,       div(2)},
    Note{C5,       div(2)},
    Note{E5,       div(1)},
    Note{D5,       div(2)},
    Note{C5,       div(2)},
    // 31
    Note{B4,       div(1)},
    Note{O,        div(1)},
    Note{D5,       div(1)},
    Note{E5,       div(1)},
    // 32
    Note{C5,       div(1)},
    Note{A4,       div(1)},
    Note{A4,       div(1)},
    Note{O,        div(1)},

    // 33
    Note{E4,       div(1)},
    Note{O,        div(1)},
    Note{C4,       div(1)},
    Note{O,        div(1)},
    // 34
    Note{D4,       div(1)},
    Note{O,        div(1)},
    Note{B4,       div(1)},
    Note{O,        div(1)},
    // 35
    Note{C4,       div(1)},
    Note{O,        div(1)},
    Note{A4,       div(1)},
    Note{O,        div(1)},
    // 36
    Note{G4_Sharp,       div(1)},
    Note{O,        div(1)},
    Note{B4,       div(1)},
    Note{O,        div(1)},

    // 37
    Note{E4,       div(1)},
    Note{O,        div(1)},
    Note{C4,       div(1)},
    Note{O,        div(1)},
    // 38
    Note{D4,       div(1)},
    Note{O,        div(1)},
    Note{B4,       div(1)},
    Note{O,        div(1)},
    // 39
    Note{C4,       div(1)},
    Note{E4,       div(1)},
    Note{A4,       div(1)},
    Note{A4,       div(1)},
    // 40
    Note{G4_Sharp, div(1)},
    Note{O,        div(1)},
    Note{O,        div(1)},
    Note{O,        div(1)},
};

constexpr inline AudioPlayer::Audio Korobeiniki(musical_score.begin(), musical_score.end());
